### ISSUE TITLE
Update Progress: 1.15

### ISSUE THREAD

**Issue by changkun** [golang-design/under-the-hood#1]
声明：本项目已经捐赠给 [golang.design](golang.design) initiative 进行创作。

Notice：The project has donated to the [golang.design](golang.design) initiative for future creation.

**Comment by xuanjiazhen** [comment]
建议把进度情况放到readme

**Comment by myonlyzzy** [comment]
写的非常好.是我见过的关于golang调度部分解读的最详尽的文章.

**Comment by changkun** [comment]
目前正文内容已经更新到 1.12beta2，根据 #3 的动机，以下内容需要被纳入写作范围内：

- 1.12 Release Note: https://tip.golang.org/doc/go1.12
- 1.12 Issue tracker: https://github.com/golang/go/milestone/65
- 1.12 vs 1.11 变化对比: https://github.com/changkun/go/pull/4/files

- 相对重要的改进
  + 抢占式调度：https://github.com/golang/go/issues/24543
    - 设计文档： https://github.com/golang/proposal/blob/master/design/24543-non-cooperative-preemption.md
  + 并发 GC：https://github.com/golang/go/issues/17503
    - 设计文档：https://github.com/golang/proposal/blob/master/design/17503-eliminate-rescan.md
  + 并发 GC：https://github.com/golang/go/issues/26903
    - 设计文档：https://github.com/golang/proposal/blob/master/design/26903-simplify-mark-termination.md
  + Go 程序 ABI : https://github.com/golang/go/issues/27539
    - 设计文档：https://github.com/golang/proposal/blob/master/design/27539-internal-abi.md
- 比较重要的 bug:
  + 并发 GC 的问题：https://github.com/golang/go/issues/27993
  + 编译器残留内存：https://github.com/golang/go/issues/22350
    - 设计文档：https://docs.google.com/document/d/1un-Jn47yByHL7I0aVIP_uVCMxjdM5mpelJhiKlIqxkE/edit#

**Comment by changkun** [comment]
Go 1.13 重要更新汇总：

- 全新的支持过程间逃逸分析的实现：https://github.com/golang/go/issues/23109
- 全新的 error 实现：https://github.com/golang/go/issues/29934, https://github.com/golang/go/issues/30468
- 新引入的抢占条件：https://github.com/golang/go/issues/10958
- 全新的 sync.Pool 实现：https://github.com/golang/go/issues/22950
- TBA

**Comment by changkun** [comment]
Go 1.14（看起来 Go 1.13 并完不成这些坑）：

- 新引入的抢占条件：https://github.com/golang/go/issues/10958
- 全新的 error 实现：https://github.com/golang/go/issues/29934, https://github.com/golang/go/issues/30468

**Comment by changkun** [comment]
## 参与合著的流程

1. 参与合著的流程：fork --> pull request --> review --> merge 的流程来参与共同写作。
2. 当全书初稿形成后，会创建 team 号，根据参与的写作量（根据字数、章节数等因素加权计算）来决定第一、第二、第三等作者的顺序，写作量较小则会成为贡献者出现在贡献者名单中。
3. 写作内容不能与其他人冲突，当确定编写某个章节时候，创建一个 issue，来确保其他人不会产生冲突，写作进度统一在 issue#1 管理。
4. 当发起一个章节的写作时，写作时长不能超过四个星期，否则会标记为超时，取消 issue 给定的写作计划，并有其他人进行处理。
5. 不允许出现抄袭，所有文字、图表必须自行创作，并在 `book/assets` 中上传制作时的源文件和目标文件。
6. 若需引入文献，引用必须参考学术引用的规则，例如：文献在文章中使用 Author–Year and Numerical 格式引用 (natbib)，优先引用一级文献。
7. 已完成初稿的章节不计入合著流程。

**Comment by changkun** [comment]
Misc:

- Fairness in select statement: https://github.com/golang/go/issues/21806

**Comment by changkun** [comment]
Go 1.15:

- [ ] go linker: https://docs.google.com/document/d/1D13QhciikbdLtaI67U6Ble5d_1nsI4befEd6_k1z91U/view#

**Comment by changkun** [comment]
声明：本项目已经终止维护，笔者在此特别感谢所有对支持、阅读和关注过此书的读者。

Notice：The project has terminated its maintenance, there will be no future plans for the writing of the book. The author would like to thank everybody who had supported, read and followed the writing of the book.

**Comment by changkun** [comment]
声明：本项目已经捐赠给 [golang.design](golang.design) initiative 进行创作。

Notice：The project has donated to the [golang.design](golang.design) initiative for future creation.

**Comment by changkun** [comment]
本 issue 下所有列出的 issue 均已归档到 [golang.design/history](https://golang.design/history) 中，参见 https://github.com/golang-design/history/commit/f9c984145f64940a78924c04019a6a780c51407d。

[golang.design/history](https://golang.design/history) 是一个比此 issue 更加广泛的超集，读者可以在该网站中进行更高效的查询，同样 [golang.design/history](https://golang.design/history) 中的内容也会反过来影响本书的写作。

考虑到上述原因，故关闭此 issue。
