### ISSUE TITLE
一个小小的错别字

### ISSUE THREAD

**Issue by l-qing** [golang-design/under-the-hood#46]
## 实际描述

- 文件路径：gosrc/runtime/stack.go
- 原文段落： L117

https://github.com/golang-design/under-the-hood/blob/b4fe13254f90b8c6688b17483a2c903be6400874/gosrc/runtime/stack.go#L117

- 文件路径：book/zh-cn/part2runtime/ch06sched/preemption.md
- 原文段落： L159

https://github.com/golang-design/under-the-hood/blame/b4fe13254f90b8c6688b17483a2c903be6400874/book/zh-cn/part2runtime/ch06sched/preemption.md#L159

## 预期描述

```
// 必须比任何实际的 SP 都要大 
```

##
仅仅只是一个小问题，但看到了，就顺便来提一提，希望能更完美。
文章内容令我收获颇丰，谢谢作者的无私奉献！

**Comment by changkun** [comment]
pr welcome
