### ISSUE TITLE
当代码片段只有1行时，在Safari浏览器中的显示有点异常。

### ISSUE THREAD

**Issue by l-qing** [golang-design/under-the-hood#53]
## 问题描述
当代码片段只有1行时，在Safari浏览器中的显示有点异常。

前面的行号1和具体的代码间隔很近.
只要代码片段有2行,显示的效果都是正常的.

在macOS上的Chrome浏览器上显示正常.
在macOS的Safari和iOS的Safari上显示的都有问题.
但是macOS的Safari上有个滑动块,拖动后可以显示正常.而iOS的Safari看不到具体的滑动块.

具体的浏览器版本见图

## 文章地址:
https://golang.design/under-the-hood/zh-cn/part1basic/ch04errors/value/

## 附图
![macOS](https://user-images.githubusercontent.com/9499086/94931203-0d83ab00-04fa-11eb-8450-0659762c9018.png)
![iOS](https://user-images.githubusercontent.com/9499086/94931181-06f53380-04fa-11eb-8729-9fb391c43f58.jpeg)

**Comment by changkun** [comment]
很不幸，也许是一个 webkit 的 bug。原因是 webkit 没有妥善处理单行的 overflow-x。

考虑此问题比较微小，可做隐藏处理，不建议在此问题上花时间。
